enable_relay = true
http_bind_addr = "0.0.0.0:3341"
enable_quic_addr_discovery = false
enable_metrics = true
metrics_bind_addr = "127.0.0.1:9098"
access = "everyone"

[limits]
accept_conn_limit = 20.0
accept_conn_burst = 40

[limits.client.rx]
bytes_per_second = 2097152
max_burst_bytes = 8388608
